/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRM;

/**
 *
 * @author Loo Alex
 */
public class frm_GASimulation extends javax.swing.JFrame {

    /**
     * Creates new form frm_GASimulation
     */
    public frm_GASimulation() {
        initComponents();
        initMap();
    }
    
    public void initMap(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOutputDetail = new javax.swing.JTabbedPane();
        tabMap = new javax.swing.JPanel();
        jXMapViewerCustom1 = new Entity.GUI_Entity.DataMap.JXMapViewerCustom();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tabPortOutputDetail = new javax.swing.JPanel();
        tabShipRouteDetail = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpShipSelection = new javax.swing.JPanel();
        lblShipCode = new javax.swing.JLabel();
        lblShipDescription = new javax.swing.JLabel();
        lblShipCategory = new javax.swing.JLabel();
        lblShipBunkerCapacity = new javax.swing.JLabel();
        lblShipCapacity = new javax.swing.JLabel();
        lblIdealSpeed = new javax.swing.JLabel();
        lblMinSpeed = new javax.swing.JLabel();
        lblMaxSpeed = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboShipCode = new javax.swing.JComboBox<>();
        txtShipCapacity = new javax.swing.JTextField();
        txtIdealSpeed = new javax.swing.JTextField();
        txtMinSpeed = new javax.swing.JTextField();
        txtMaxSpeed = new javax.swing.JTextField();
        txtShipDescription = new javax.swing.JTextField();
        txtShipCategory = new javax.swing.JTextField();
        txtShipBunkerCapacity = new javax.swing.JTextField();
        jpDisplayStatus = new javax.swing.JPanel();
        lblDisplayStatus = new javax.swing.JLabel();
        txtFuelBunkered = new javax.swing.JTextField();
        lblChosenSpeed = new javax.swing.JLabel();
        lblPortTo = new javax.swing.JLabel();
        lblTravelFuelCost = new javax.swing.JLabel();
        txtChosenSpeed = new javax.swing.JTextField();
        txtPortTo = new javax.swing.JTextField();
        lblShipBunkerLevel = new javax.swing.JLabel();
        lblPortFromSelected = new javax.swing.JLabel();
        txtLoadedCapacity = new javax.swing.JTextField();
        lblFuelBunkered = new javax.swing.JLabel();
        lblFuelBunkerCost = new javax.swing.JLabel();
        txtShipBunkerLevel = new javax.swing.JTextField();
        cboPortFromSelected = new javax.swing.JComboBox<>();
        lblLoadedCapacity = new javax.swing.JLabel();
        txtFuelBunkerCost = new javax.swing.JTextField();
        txtTravelFuelCost = new javax.swing.JTextField();
        lblOperationalCost = new javax.swing.JLabel();
        txtOperationalCost = new javax.swing.JTextField();
        lblTimeTaken = new javax.swing.JLabel();
        txtTimeTaken3 = new javax.swing.JTextField();
        lblDistance = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        jpPortSelection = new javax.swing.JPanel();
        TitlePortSelection = new javax.swing.JLabel();
        jpPortComboArea = new javax.swing.JPanel();
        jpRouteDisplay = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("frameGASimulation"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1500, 800));

        tabMap.setName(""); // NOI18N
        tabMap.setPreferredSize(new java.awt.Dimension(800, 458));

        jXMapViewerCustom1.setPreferredSize(new java.awt.Dimension(800, 452));

        jButton2.setText("Add Port");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Clear Port");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXMapViewerCustom1Layout = new javax.swing.GroupLayout(jXMapViewerCustom1);
        jXMapViewerCustom1.setLayout(jXMapViewerCustom1Layout);
        jXMapViewerCustom1Layout.setHorizontalGroup(
            jXMapViewerCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        jXMapViewerCustom1Layout.setVerticalGroup(
            jXMapViewerCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXMapViewerCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabMapLayout = new javax.swing.GroupLayout(tabMap);
        tabMap.setLayout(tabMapLayout);
        tabMapLayout.setHorizontalGroup(
            tabMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXMapViewerCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabMapLayout.setVerticalGroup(
            tabMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMapViewerCustom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        tabOutputDetail.addTab("Map", tabMap);

        tabPortOutputDetail.setPreferredSize(new java.awt.Dimension(800, 458));

        javax.swing.GroupLayout tabPortOutputDetailLayout = new javax.swing.GroupLayout(tabPortOutputDetail);
        tabPortOutputDetail.setLayout(tabPortOutputDetailLayout);
        tabPortOutputDetailLayout.setHorizontalGroup(
            tabPortOutputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        tabPortOutputDetailLayout.setVerticalGroup(
            tabPortOutputDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        tabOutputDetail.addTab("Ports Detail", tabPortOutputDetail);

        tabShipRouteDetail.setPreferredSize(new java.awt.Dimension(800, 458));

        javax.swing.GroupLayout tabShipRouteDetailLayout = new javax.swing.GroupLayout(tabShipRouteDetail);
        tabShipRouteDetail.setLayout(tabShipRouteDetailLayout);
        tabShipRouteDetailLayout.setHorizontalGroup(
            tabShipRouteDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        tabShipRouteDetailLayout.setVerticalGroup(
            tabShipRouteDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        tabOutputDetail.addTab("Ship Route Detail", tabShipRouteDetail);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jpShipSelection.setPreferredSize(new java.awt.Dimension(530, 700));

        lblShipCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblShipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipCode.setText("Ship Code");

        lblShipDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipDescription.setText("Ship Description");

        lblShipCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipCategory.setText("Ship Category");

        lblShipBunkerCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipBunkerCapacity.setText("Ship Bunker Capacity (Ton)");

        lblShipCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipCapacity.setText("Ship Capacity (TEU)");

        lblIdealSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdealSpeed.setText("Ideal Speed (kn)");

        lblMinSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSpeed.setText("Min Speed (kn)");

        lblMaxSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxSpeed.setText("Max Speed (kn)");
        lblMaxSpeed.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Ship Selection");

        cboShipCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboShipCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboShipCode.setPreferredSize(new java.awt.Dimension(75, 26));

        txtShipCapacity.setText("jTextField1");

        txtIdealSpeed.setText("jTextField2");

        txtMinSpeed.setText("jTextField3");

        txtMaxSpeed.setText("jTextField4");

        txtShipDescription.setText("jTextField5");

        txtShipCategory.setText("jTextField6");

        txtShipBunkerCapacity.setText("jTextField7");

        jpDisplayStatus.setPreferredSize(new java.awt.Dimension(510, 450));

        lblDisplayStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDisplayStatus.setText("Display Status");

        txtFuelBunkered.setText("jTextField6");

        lblChosenSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChosenSpeed.setText("Chosen Speed (kn) ");
        lblChosenSpeed.setFocusable(false);

        lblPortTo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPortTo.setText("Port To");

        lblTravelFuelCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTravelFuelCost.setText("Travel Fuel Cost ($) ");

        txtChosenSpeed.setText("jTextField4");

        txtPortTo.setText("jTextField5");

        lblShipBunkerLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblShipBunkerLevel.setText("Ship Bunker Level (Ton) ");

        lblPortFromSelected.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPortFromSelected.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPortFromSelected.setText("Port From");

        txtLoadedCapacity.setText("jTextField1");

        lblFuelBunkered.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuelBunkered.setText("Fuel Bunkered (Ton)");

        lblFuelBunkerCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuelBunkerCost.setText("Fuel Bunker Cost  ($)");

        txtShipBunkerLevel.setText("jTextField2");

        cboPortFromSelected.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboPortFromSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPortFromSelected.setPreferredSize(new java.awt.Dimension(75, 26));

        lblLoadedCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoadedCapacity.setText("Loaded Capacity (TEU) ");

        txtFuelBunkerCost.setText("jTextField7");

        txtTravelFuelCost.setText("jTextField3");

        lblOperationalCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOperationalCost.setText("Operational Cost ($) ");

        txtOperationalCost.setText("jTextField1");

        lblTimeTaken.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeTaken.setText("Time Taken (Hr) ");

        txtTimeTaken3.setText("jTextField2");

        lblDistance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDistance.setText("Distance (nmi) ");

        txtDistance.setText("jTextField3");

        javax.swing.GroupLayout jpDisplayStatusLayout = new javax.swing.GroupLayout(jpDisplayStatus);
        jpDisplayStatus.setLayout(jpDisplayStatusLayout);
        jpDisplayStatusLayout.setHorizontalGroup(
            jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisplayStatus))
                    .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblOperationalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTimeTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDistance, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTimeTaken3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtOperationalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFuelBunkerCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLoadedCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblShipBunkerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTravelFuelCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChosenSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPortFromSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPortTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFuelBunkered, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFuelBunkered)
                                    .addComponent(txtPortTo)
                                    .addComponent(txtFuelBunkerCost)
                                    .addComponent(cboPortFromSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChosenSpeed)
                                    .addComponent(txtTravelFuelCost)
                                    .addComponent(txtLoadedCapacity)
                                    .addComponent(txtShipBunkerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jpDisplayStatusLayout.setVerticalGroup(
            jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDisplayStatusLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblDisplayStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPortFromSelected)
                    .addComponent(cboPortFromSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPortTo)
                    .addComponent(txtPortTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuelBunkered)
                    .addComponent(txtFuelBunkered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuelBunkerCost)
                    .addComponent(txtFuelBunkerCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoadedCapacity)
                    .addComponent(txtLoadedCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipBunkerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShipBunkerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTravelFuelCost)
                    .addComponent(txtTravelFuelCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChosenSpeed)
                    .addComponent(txtChosenSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperationalCost)
                    .addComponent(txtOperationalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeTaken3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDisplayStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistance)
                    .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpShipSelectionLayout = new javax.swing.GroupLayout(jpShipSelection);
        jpShipSelection.setLayout(jpShipSelectionLayout);
        jpShipSelectionLayout.setHorizontalGroup(
            jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpShipSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDisplayStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpShipSelectionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpShipSelectionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblShipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdealSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMinSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblShipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblShipBunkerCapacity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboShipCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtShipCategory)
                    .addComponent(txtShipDescription)
                    .addComponent(txtShipBunkerCapacity)
                    .addComponent(txtShipCapacity)
                    .addComponent(txtIdealSpeed)
                    .addComponent(txtMinSpeed)
                    .addComponent(txtMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jpShipSelectionLayout.setVerticalGroup(
            jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpShipSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipCode)
                    .addComponent(cboShipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipDescription)
                    .addComponent(txtShipDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipCategory)
                    .addComponent(txtShipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipBunkerCapacity)
                    .addComponent(txtShipBunkerCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipCapacity)
                    .addComponent(txtShipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdealSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdealSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinSpeed)
                    .addComponent(txtMinSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpShipSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxSpeed)
                    .addComponent(txtMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpDisplayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMaxSpeed.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Ship Selection", jpShipSelection);

        TitlePortSelection.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitlePortSelection.setText("Port Selection");

        javax.swing.GroupLayout jpPortComboAreaLayout = new javax.swing.GroupLayout(jpPortComboArea);
        jpPortComboArea.setLayout(jpPortComboAreaLayout);
        jpPortComboAreaLayout.setHorizontalGroup(
            jpPortComboAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jpPortComboAreaLayout.setVerticalGroup(
            jpPortComboAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpRouteDisplayLayout = new javax.swing.GroupLayout(jpRouteDisplay);
        jpRouteDisplay.setLayout(jpRouteDisplayLayout);
        jpRouteDisplayLayout.setHorizontalGroup(
            jpRouteDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpRouteDisplayLayout.setVerticalGroup(
            jpRouteDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpPortSelectionLayout = new javax.swing.GroupLayout(jpPortSelection);
        jpPortSelection.setLayout(jpPortSelectionLayout);
        jpPortSelectionLayout.setHorizontalGroup(
            jpPortSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPortSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPortSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPortComboArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPortSelectionLayout.createSequentialGroup()
                        .addComponent(TitlePortSelection)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpRouteDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPortSelectionLayout.setVerticalGroup(
            jpPortSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPortSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePortSelection)
                .addGap(18, 18, 18)
                .addComponent(jpPortComboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpRouteDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Port Selection", jpPortSelection);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabOutputDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabOutputDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_GASimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_GASimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_GASimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_GASimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_GASimulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitlePortSelection;
    private javax.swing.JComboBox<String> cboPortFromSelected;
    private javax.swing.JComboBox<String> cboShipCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Entity.GUI_Entity.DataMap.JXMapViewerCustom jXMapViewerCustom1;
    private javax.swing.JPanel jpDisplayStatus;
    private javax.swing.JPanel jpPortComboArea;
    private javax.swing.JPanel jpPortSelection;
    private javax.swing.JPanel jpRouteDisplay;
    private javax.swing.JPanel jpShipSelection;
    private javax.swing.JLabel lblChosenSpeed;
    private javax.swing.JLabel lblDisplayStatus;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblFuelBunkerCost;
    private javax.swing.JLabel lblFuelBunkered;
    private javax.swing.JLabel lblIdealSpeed;
    private javax.swing.JLabel lblLoadedCapacity;
    private javax.swing.JLabel lblMaxSpeed;
    private javax.swing.JLabel lblMinSpeed;
    private javax.swing.JLabel lblOperationalCost;
    private javax.swing.JLabel lblPortFromSelected;
    private javax.swing.JLabel lblPortTo;
    private javax.swing.JLabel lblShipBunkerCapacity;
    private javax.swing.JLabel lblShipBunkerLevel;
    private javax.swing.JLabel lblShipCapacity;
    private javax.swing.JLabel lblShipCategory;
    private javax.swing.JLabel lblShipCode;
    private javax.swing.JLabel lblShipDescription;
    private javax.swing.JLabel lblTimeTaken;
    private javax.swing.JLabel lblTravelFuelCost;
    private javax.swing.JPanel tabMap;
    private javax.swing.JTabbedPane tabOutputDetail;
    private javax.swing.JPanel tabPortOutputDetail;
    private javax.swing.JPanel tabShipRouteDetail;
    private javax.swing.JTextField txtChosenSpeed;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtFuelBunkerCost;
    private javax.swing.JTextField txtFuelBunkered;
    private javax.swing.JTextField txtIdealSpeed;
    private javax.swing.JTextField txtLoadedCapacity;
    private javax.swing.JTextField txtMaxSpeed;
    private javax.swing.JTextField txtMinSpeed;
    private javax.swing.JTextField txtOperationalCost;
    private javax.swing.JTextField txtPortTo;
    private javax.swing.JTextField txtShipBunkerCapacity;
    private javax.swing.JTextField txtShipBunkerLevel;
    private javax.swing.JTextField txtShipCapacity;
    private javax.swing.JTextField txtShipCategory;
    private javax.swing.JTextField txtShipDescription;
    private javax.swing.JTextField txtTimeTaken3;
    private javax.swing.JTextField txtTravelFuelCost;
    // End of variables declaration//GEN-END:variables
}
