/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRM;

/**
 *
 * @author Loo Alex
 */
public class frm_MainSimulationPanel extends javax.swing.JFrame {

    /**
     * Creates new form frm_MainSimulationPanel
     */
    public frm_MainSimulationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMainJourney = new javax.swing.JTabbedPane();
        jpMap = new javax.swing.JPanel();
        jpMapDisplay = new javax.swing.JPanel();
        jpPortDetail = new javax.swing.JPanel();
        sclPortDetail = new javax.swing.JScrollPane();
        dtPortDetail = new javax.swing.JTable();
        jpDemanDetail = new javax.swing.JPanel();
        sclDemandDetail = new javax.swing.JScrollPane();
        dtDemandDetail = new javax.swing.JTable();
        jpShipDetail = new javax.swing.JPanel();
        lblTitleShipdetailPane = new javax.swing.JLabel();
        cboShipCategory = new javax.swing.JComboBox<>();
        lblShipCode = new javax.swing.JLabel();
        txtShipCode = new javax.swing.JTextField();
        lblShipDescription = new javax.swing.JLabel();
        txtShipDescription = new javax.swing.JTextField();
        lblShipCategory = new javax.swing.JLabel();
        lblFuelCapacity = new javax.swing.JLabel();
        txtFuelCapacity = new javax.swing.JTextField();
        lblShipCapacity = new javax.swing.JLabel();
        txtShipCapacity = new javax.swing.JTextField();
        jpOutput = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation Board");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 720));
        setSize(new java.awt.Dimension(1200, 600));

        tabMainJourney.setName("Map"); // NOI18N

        javax.swing.GroupLayout jpMapDisplayLayout = new javax.swing.GroupLayout(jpMapDisplay);
        jpMapDisplay.setLayout(jpMapDisplayLayout);
        jpMapDisplayLayout.setHorizontalGroup(
            jpMapDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jpMapDisplayLayout.setVerticalGroup(
            jpMapDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMapLayout = new javax.swing.GroupLayout(jpMap);
        jpMap.setLayout(jpMapLayout);
        jpMapLayout.setHorizontalGroup(
            jpMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMapLayout.createSequentialGroup()
                .addComponent(jpMapDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMapLayout.setVerticalGroup(
            jpMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMapDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabMainJourney.addTab("Map", jpMap);

        dtPortDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sequence Number", "Port ID", "Port Description", "Fuel Price", "Supplies Amount", "Demand Amount", "Total Demands AH", "Time Visited"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dtPortDetail.setPreferredSize(new java.awt.Dimension(200, 80));
        sclPortDetail.setViewportView(dtPortDetail);
        if (dtPortDetail.getColumnModel().getColumnCount() > 0) {
            dtPortDetail.getColumnModel().getColumn(0).setResizable(false);
            dtPortDetail.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jpPortDetailLayout = new javax.swing.GroupLayout(jpPortDetail);
        jpPortDetail.setLayout(jpPortDetailLayout);
        jpPortDetailLayout.setHorizontalGroup(
            jpPortDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclPortDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        jpPortDetailLayout.setVerticalGroup(
            jpPortDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPortDetailLayout.createSequentialGroup()
                .addComponent(sclPortDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabMainJourney.addTab("Port", jpPortDetail);

        dtDemandDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Demand ID", "From PortID", "To PortID", "Demand Description", "Containter CategoryID", "Total Demand", "Total Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        sclDemandDetail.setViewportView(dtDemandDetail);

        javax.swing.GroupLayout jpDemanDetailLayout = new javax.swing.GroupLayout(jpDemanDetail);
        jpDemanDetail.setLayout(jpDemanDetailLayout);
        jpDemanDetailLayout.setHorizontalGroup(
            jpDemanDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDemanDetailLayout.createSequentialGroup()
                .addComponent(sclDemandDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDemanDetailLayout.setVerticalGroup(
            jpDemanDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclDemandDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        tabMainJourney.addTab("Demands", jpDemanDetail);

        lblTitleShipdetailPane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleShipdetailPane.setText("Select Ship Details");

        cboShipCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboShipCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShipCategoryActionPerformed(evt);
            }
        });

        lblShipCode.setText("Ship Code");

        txtShipCode.setText("jTextField1");
        txtShipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipCodeActionPerformed(evt);
            }
        });

        lblShipDescription.setText("Ship Description");

        txtShipDescription.setText("txtShipDescription");
        txtShipDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipDescriptionActionPerformed(evt);
            }
        });

        lblShipCategory.setText("Ship Category");

        lblFuelCapacity.setText("Fuel Capacity (Ton)");

        txtFuelCapacity.setText("Fuel Capacity/Ton");
        txtFuelCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelCapacityActionPerformed(evt);
            }
        });

        lblShipCapacity.setText("Ship Capacity (TEU)");

        txtShipCapacity.setText("Capacity/TEU");
        txtShipCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipCapacityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpShipDetailLayout = new javax.swing.GroupLayout(jpShipDetail);
        jpShipDetail.setLayout(jpShipDetailLayout);
        jpShipDetailLayout.setHorizontalGroup(
            jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpShipDetailLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitleShipdetailPane)
                        .addGroup(jpShipDetailLayout.createSequentialGroup()
                            .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblFuelCapacity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(lblShipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblShipCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblShipDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtShipDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(cboShipCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtShipCode)
                                .addComponent(txtFuelCapacity, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jpShipDetailLayout.createSequentialGroup()
                        .addComponent(lblShipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtShipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpShipDetailLayout.setVerticalGroup(
            jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpShipDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleShipdetailPane)
                .addGap(23, 23, 23)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipCode)
                    .addComponent(txtShipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipDescription)
                    .addComponent(txtShipDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboShipCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShipCategory))
                .addGap(16, 16, 16)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuelCapacity)
                    .addComponent(txtFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpShipDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipCapacity)
                    .addComponent(txtShipCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpOutputLayout = new javax.swing.GroupLayout(jpOutput);
        jpOutput.setLayout(jpOutputLayout);
        jpOutputLayout.setHorizontalGroup(
            jpOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpOutputLayout.setVerticalGroup(
            jpOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpShipDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabMainJourney)
                .addContainerGap())
            .addComponent(jpOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMainJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jpShipDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jpOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabMainJourney.getAccessibleContext().setAccessibleName("ControlPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboShipCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShipCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboShipCategoryActionPerformed

    private void txtShipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipCodeActionPerformed

    private void txtShipDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipDescriptionActionPerformed

    private void txtFuelCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelCapacityActionPerformed

    private void txtShipCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipCapacityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_MainSimulationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_MainSimulationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_MainSimulationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_MainSimulationPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_MainSimulationPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboShipCategory;
    private javax.swing.JTable dtDemandDetail;
    private javax.swing.JTable dtPortDetail;
    private javax.swing.JPanel jpDemanDetail;
    private javax.swing.JPanel jpMap;
    private javax.swing.JPanel jpMapDisplay;
    private javax.swing.JPanel jpOutput;
    private javax.swing.JPanel jpPortDetail;
    private javax.swing.JPanel jpShipDetail;
    private javax.swing.JLabel lblFuelCapacity;
    private javax.swing.JLabel lblShipCapacity;
    private javax.swing.JLabel lblShipCategory;
    private javax.swing.JLabel lblShipCode;
    private javax.swing.JLabel lblShipDescription;
    private javax.swing.JLabel lblTitleShipdetailPane;
    private javax.swing.JScrollPane sclDemandDetail;
    private javax.swing.JScrollPane sclPortDetail;
    private javax.swing.JTabbedPane tabMainJourney;
    private javax.swing.JTextField txtFuelCapacity;
    private javax.swing.JTextField txtShipCapacity;
    private javax.swing.JTextField txtShipCode;
    private javax.swing.JTextField txtShipDescription;
    // End of variables declaration//GEN-END:variables
}
