/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRM;

/**
 *
 * @author Loo Alex
 * This is the open page of the system, when someone sign in successfully
 */
public class frm_OpenPanel_Main extends javax.swing.JFrame {

    /**
     * Creates new form frm_SimulationPanel
     */
    public frm_OpenPanel_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuBar = new javax.swing.JMenuBar();
        mnSimulationMenu = new javax.swing.JMenu();
        miGASimulation = new javax.swing.JMenuItem();
        mnShip = new javax.swing.JMenu();
        miViewShip = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miViewPorts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");

        mnSimulationMenu.setText("Simulation");

        miGASimulation.setText("Genetic Algo");
        miGASimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGASimulationActionPerformed(evt);
            }
        });
        mnSimulationMenu.add(miGASimulation);

        MainMenuBar.add(mnSimulationMenu);

        mnShip.setText("Ship");

        miViewShip.setText("View Ship Categories");
        miViewShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewShipActionPerformed(evt);
            }
        });
        mnShip.add(miViewShip);

        MainMenuBar.add(mnShip);

        jMenu3.setText("Port");

        miViewPorts.setText("View Ports");
        miViewPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewPortsActionPerformed(evt);
            }
        });
        jMenu3.add(miViewPorts);

        MainMenuBar.add(jMenu3);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-GA Simulation menu
    private void miGASimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGASimulationActionPerformed
        new frm_GASimulation().setVisible(true);
        
    }//GEN-LAST:event_miGASimulationActionPerformed

    private void miViewShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miViewShipActionPerformed
        // TODO add your handling code here:
        new frm_ViewShipCategory().setVisible(true);
    }//GEN-LAST:event_miViewShipActionPerformed

    private void miViewPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miViewPortsActionPerformed
        // TODO add your handling code here:
        new frm_ViewPort().setVisible(true);
    }//GEN-LAST:event_miViewPortsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_OpenPanel_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_OpenPanel_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_OpenPanel_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_OpenPanel_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_OpenPanel_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem miGASimulation;
    private javax.swing.JMenuItem miViewPorts;
    private javax.swing.JMenuItem miViewShip;
    private javax.swing.JMenu mnShip;
    private javax.swing.JMenu mnSimulationMenu;
    // End of variables declaration//GEN-END:variables
}
